// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsFob0Fo3A5fDOdrulUAwD7v4-Hj5540',
    appId: '1:403739509222:web:7c39bb1ce4c15da8489627',
    messagingSenderId: '403739509222',
    projectId: 'antbery-49fb6',
    authDomain: 'antbery-49fb6.firebaseapp.com',
    storageBucket: 'antbery-49fb6.appspot.com',
    measurementId: 'G-1ZW8H4J014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGNzNQEUuRLmDMsW1M7SvLvtPyaKlyBs',
    appId: '1:403739509222:android:a5f80a5a6fe3038f489627',
    messagingSenderId: '403739509222',
    projectId: 'antbery-49fb6',
    storageBucket: 'antbery-49fb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQtx0RRwczusTcgmR_2g0mJfdyi_uKLTk',
    appId: '1:403739509222:ios:59e0a0641255dbf9489627',
    messagingSenderId: '403739509222',
    projectId: 'antbery-49fb6',
    storageBucket: 'antbery-49fb6.appspot.com',
    iosBundleId: 'com.example.antbery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQtx0RRwczusTcgmR_2g0mJfdyi_uKLTk',
    appId: '1:403739509222:ios:d5c49140853f2bd7489627',
    messagingSenderId: '403739509222',
    projectId: 'antbery-49fb6',
    storageBucket: 'antbery-49fb6.appspot.com',
    iosBundleId: 'com.example.antbery.RunnerTests',
  );
}
